# -*- coding: utf-8 -*-
"""config_bert

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gM8RW2im6YFTncak2nHUbVI_Y3pz6ndb
"""

import transformers

BERT_PATH = 'bert-base-cased'
EPOCHS = 3
MAX_LEN = 512
BATCH_SIZE = 4
VALID_BATCH_SIZE = 2
TOKENIZER = transformers.BertTokenizer.from_pretrained(BERT_PATH)

